doctrine/DoctrinePHPCRBundle

Command/PhpcrShellCommand.php
composer.json

The way PHPCRSH is instantiated has changed as of 1.0 and I don't want to have a bunch of legacy code for alpha BC in the stable release, so this is a BC break with existing behavior for the alpha version.
This is (still) a suggested dependency, people who have installed the phpcr-shell will simply need to perform a minor upgrade.
Note this depends on the 1.0 release of [PHPCRSH](https://github.com/phpcr/phpcr-shell)

Changed PHPCR Shell instantiation.

---

DependencyInjection/Configuration.php
DependencyInjection/DoctrinePHPCRExtension.php
Resources/config/odm.xml
Tests/Unit/DependencyInjection/ConfigurationTest.php

This PR allows the namespace alias used for the attribute translation strategy to be configured.
It also adds the translation strategies to the DI container, which paves the way for dynamically registering new strategies in the future if required.
See documentation PR: https://github.com/symfony-cmf/symfony-cmf-docs/pull/653

Enable locale namespace alias to be configured

---

.travis.yml
Form/ChoiceList/PhpcrOdmQueryBuilderLoader.php
Form/Type/DocumentType.php
Tests/Functional/Form/ChoiceList/PhpcrOdmQueryBuilderLoaderTest.php
Tests/Functional/Form/PHPCRTypeGuesserTest.php
Tests/Functional/Form/Type/DocumentTypeTest.php
Tests/Resources/DataFixtures/PHPCR/LoadData.php

supersedes https://github.com/doctrine/DoctrinePHPCRBundle/pull/193

[Forms] Fix PhpcrOdmQueryBuilderLoader and depend on symfony version that fixed DoctrineType

---

.travis.yml
composer.json

Tests should tell if any deprecated interfaces of Symfony are used. If not, then the bundle is defacto compatible with 3.0

Allow symfony 3.0 components

---

Form/PhpcrOdmTypeGuesser.php
Tests/Functional/Form/PHPCRTypeGuesserTest.php

not quite sure if this is correct .. furthermore we of course cannot just update it .. but we have to add some BC logic there .. not sure what the most elegant way is here ..

refactored read_only option for Symfony 2.8

---

.gitignore
.php_cs
Command/DoctrineCommandHelper.php
composer.json

The goal of this bridge is to provide an automatic configuration for php-cs-fixer based from StyleCI configuration.
I also added a Makefile to run cs and test with simple commands: `make cs` / `make test`.
I can remove it if you don't want to deal with Makefiles.

StyleCI config bridge

---

.travis.yml

hopefully this change will get us rid of the failures because of deprecated constructs.

do not treat deprecation warnings as errors in maintenance branch

---

Form/ChoiceList/PhpcrOdmQueryBuilderLoader.php

see my comment on the source code of the commit that introduced that f393c067ca11f24175d3a5f450329fb2d3129fca

skip query when there is no valid id

---

EventListener/LocaleListener.php
Tests/Unit/EventListener/LocaleListenerTest.php

Follow on from https://github.com/doctrine/DoctrinePHPCRBundle/pull/222
I have changed the default strategy to be MERGE as requested by @dbu 
Also this is a branch off 1.2 rather than master.

Fix explicit null passed as fallback 1.2

---

CacheWarmer/UniqueNodeTypeCacheWarmer.php
DoctrinePHPCRBundle.php
OptionalCommand/ODM/VerifyUniqueNodeTypesMappingCommand.php
Resources/config/odm.xml

This is a companion to doctrine/phpcr-odm#667 which introduces the designation of documents using unique node types at the mapping level in order to support real outer joins in Jackrabbit. This PR introduces a shell command and hooks the verification into the cache warming process.

Verification of unique node type in support of real outer joins

---

.travis.yml
Tests/Resources/Document/TestDocument.php
Tests/Unit/Form/Type/PathTypeTest.php
composer.json

revert hack of #231 once https://github.com/symfony/symfony/commit/1bdd127938058a1f34fd0bc883ebb9e4d6ccf67d is included in a 2.7 release.

revert locking tests to dev version of symfony

---

.travis.yml
composer.json

Using a conflict rule instead of listing all allowed versions with require seems to let Composer properly resolve the desired Symfony versions without having to enforce them.

update version constraint for FrameworkBundle

---

CacheWarmer/UniqueNodeTypeCacheWarmer.php

Static was removed from this method in 1.3: https://github.com/doctrine/phpcr-odm/pull/667 (not sure why though) This now errors when warming up the cache.

[Bugfix] Do not call non-static method as static method

---

CHANGELOG.md
DependencyInjection/DoctrinePHPCRExtension.php
composer.json

This applies @dbu's changes from #249 and on top of that readds conflict rules which have been removed in #246. This way, we can work around issues like composer/composer#3754 and composer/composer#4735.

 default to not check login on backend even in dev mode

---

CHANGELOG.md
Command/LoadFixtureCommand.php
Command/MigratorMigrateCommand.php
Command/NodeTypeRegisterCommand.php
Command/PhpcrShellCommand.php
Command/RepositoryInitCommand.php
DependencyInjection/Configuration.php
DependencyInjection/DoctrinePHPCRExtension.php
OptionalCommand/Jackalope/JackrabbitCommand.php
OptionalCommand/ODM/DocumentConvertTranslationCommand.php
OptionalCommand/ODM/InfoDoctrineCommand.php
OptionalCommand/ODM/VerifyUniqueNodeTypesMappingCommand.php
Tests/Unit/DependencyInjection/ConfigurationTest.php

Main PR: https://github.com/jackalope/jackalope-jackrabbit/pull/130

Added curl-options to configuration

---

CHANGELOG.md
Resources/config/jackalope.xml

The following issue in Sulu was reported: https://github.com/sulu/sulu/issues/3106
Long story short: Currently utf8 emojis like "🎄" are not working with jackalope-doctrine-dbal, because it uses the limited `utf8` charset instead of `utf8mb4`. I thought I can simply change the charset in doctrine dbal, but jackalope seemed to ignore it.
I found out that the service configuration didn't pass the `Connection` class, so it was using some default values instead of what has been defined in the DoctrineBundle. So the tables defined in the [RepositorySchema](https://github.com/jackalope/jackalope-doctrine-dbal/blob/75bfb54453f224a9e848cee70cc85bf8d48c4556/src/Jackalope/Transport/DoctrineDBAL/RepositorySchema.php#L37) did not use the `default_table_options` defined in the application …

added connection to service configuration of RepositorySchema

---

.travis.yml
DependencyInjection/DoctrinePHPCRExtension.php
Tests/Unit/Form/DataTransformer/PHPCRNodeToPathTransformerTest.php
Tests/Unit/Form/DataTransformer/PHPCRNodeToUuidTransformerTest.php

to avoid deprecation warnings with symfony 3.3+ and be future proof for symfony 4.

use ChildDefinition over DefinitionDecorator when available

---

Resources/config/jackalope.xml

Cleaned up version of #273
Previous PR used ID `jackalope_doctrine_dbal.default_connection` instead of `doctrine_phpcr.jackalope_doctrine_dbal.default_connection`
Allows for multiple dbal connections and defining the connection to use in doctrine_phpcr:
```yaml
doctrine_phpcr:
session:
backend:
connection: a_connection_name
```
`doctrine.dbal.default_connection` does not exist when multiple connections are defined like this for example:
```yaml
doctrine:
dbal:
default_connection: main
connections:
main:
driver: pdo_mysql
host: '%database_host%'
port: '%database_port%'
dbname: '%database_name%'
user: '%database_user%'
password: '%database_password%'
charset: utf8mb4
default_table_options:
charset: utf8mb4
collate: utf8mb4_unicode_ci
secondary:
driver: pdo_sqlite
charset: utf8mb4 …
```

Use correct dbal connection if multiple are configured

---

Command/LoadFixtureCommand.php

This allows to load fixtures from a bundless application like the one created with symfony/flex. This is a port of https://github.com/doctrine/DoctrineFixturesBundle/pull/192.

Add kernel root directory to fixtures location paths

---

Tests/Initializer/GenericInitializerTest.php
Tests/Unit/EventListener/LocaleListenerTest.php
Tests/Unit/Form/DataTransformer/DocumentToPathTransformerTest.php
Tests/Unit/Form/DataTransformer/PHPCRNodeToPathTransformerTest.php
Tests/Unit/Form/DataTransformer/PHPCRNodeToUuidTransformerTest.php
Tests/Unit/Form/Type/PHPCRReferenceTypeTest.php
Tests/Unit/Form/Type/PathTypeTest.php
Tests/Unit/Initializer/InitializerManagerTest.php
composer.json

Use [PSR-1](http://www.php-fig.org/psr/psr-1/#namespace-and-class-names) while extending PHPUnit TestCase class. This will help us when to migrate to PHPUnit 6, that [no longer support snake case namespaces](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-6.0.md#changed-1).

Use PSR-1 for PHPUnit TestCase

---

.travis.yml
DependencyInjection/DoctrinePHPCRExtension.php
ManagerRegistry.php
Resources/config/phpcr.xml
Tests/Unit/DependencyInjection/DoctrinePHPCRExtensionTest.php

preparations for symfony 4.0

---

DependencyInjection/Compiler/InitializerPass.php

Since #96, initializers no longer have to be public. This remove the hard check introduced in #50.

Allow initializer services to be private

---

src/Resources/config/phpcr.xml
src/Resources/views/Collector/phpcr.html.twig

Since the new syntax (`DoctrinePHPCR/Collector/phpcr.html.twig`) is already used in the templates, I updated the paths where the old syntax (`DoctrinePHPCRBundle:Collector:phpcr`) was used to ensure compatibility with symfony ^3.4 || ^4.0
Fixes #307

Fixes paths of twig templates

---

src/Resources/config/phpcr.xml

As reported by @damienflament, I forgot a `@` in my previous PR #311 
Sorry about that.

Add missing @ in data collector template path

---

src/Resources/config/odm.xml

looks like #287 went too far, as the doctrine bridge relies on some of these parameters.

re-add class parameters used by the doctrine bridge

---

src/DependencyInjection/DoctrinePHPCRExtension.php

With this PR the folder `src/Doument` which stands for `App\Document` is added to mapped paths for annotation driver.

add app's document path to the mapped paths

---

src/Command/NodeDumpCommand.php
tests/Fixtures/App/DataFixtures/PHPCR/LoadData.php
tests/Functional/Command/NodeDumpCommandTest.php

I fixed it by changing `getParameterOption` to `hasOption` - I also added a functional test for it. 
The problem with `getParameterOption` is that it expects the raw parameter name (which would be `--max_line_length` instead of just `max_line_length`) so this check always returns false, even if the option is actually present. 
Any feedback is welcome!

`--max_line_length` option is ignored in NodeDumpCommand

---

src/DependencyInjection/DoctrinePHPCRExtension.php

With this issue, `App\Document\` namespace was looked up in directory:
- `src/`; other than
- `src/Document`
This also causes issue with Data Fixtures in some use cases where:
- Symfony is on `APP_ENV=prod` mode and composer install with `--no-dev`; and
- Data fixture which use `doctrine/doctrine-fixtures-bundle` (e.g., AppFixture) is located within `src/`
```php
// Running bin/console cache:warmup
PHP Fatal error:  Class 'Doctrine\Bundle\FixturesBundle\Fixture'
not found in src/symfony-project/src/DataFixtures/AppFixtures.php on line ??
```
As a result, this issue has similar symptom as shown in https://github.com/doctrine/DoctrineFixturesBundle/issues/225 but with different cause

Fix whole src/ dir included in mapping lookup

---

DependencyInjection/DoctrinePHPCRExtension.php

When having multiple sessions defined with the same connection the `doctrine.event_listener` is added multiple times. I think it should only be added once per configuration
> bin/console debug:container doctrine_phpcr.jackalope_doctrine_dbal.schema_listener
Before:
```
---------------- -------------------------------------------------------------------------------------
Option           Value
---------------- -------------------------------------------------------------------------------------
Service ID       doctrine_phpcr.jackalope_doctrine_dbal.schema_listener
Class            Doctrine\Bundle\PHPCRBundle\EventListener\JackalopeDoctrineDbalSchemaListener
Tags             doctrine.event_listener (connection: , event: postGenerateSchema, lazy: 1)
doctrine.event_listener (connection: , …
```

Avoid add multiple doctrine.event_listener tags with same options

---

DependencyInjection/DoctrinePHPCRExtension.php

Currently the problem is that the following file is loaded once and has a hard reference the default connection: https://github.com/doctrine/DoctrinePHPCRBundle/blob/master/src/Resources/config/jackalope_doctrine_dbal.xml#L14
But if the default session is not a doctrine_dbal session the connection service doesn't exist thats why the services default should be set to the first dbal connection.
Example config where the error happens:
```yaml
doctrine_phpcr:
session:
sessions:
default:
backend:
type: jackrabbit
url: 'http://127.0.0.1:8080/server'
live:
backend:
type: jackrabbit
url: 'http://127.0.0.1:8080/server'
migration:
backend:
type: doctrinedbal
```

Fix problem with multiple mixed typed sessions when default is not a dbal session

---

composer.json
tests/Functional/BaseTestCase.php
tests/Unit/DependencyInjection/DoctrinePHPCRExtensionTest.php

Currently some tests fail because some sub bundles are access kernel.project_dir and kernel.container_class parameter in there class. To avoid this problems they are now set in the test. Fix also assertEquals third parameter need to be a string when running tests on newer phpunit version.

Fix tests on master branch

---

.styleci.yml
CHANGELOG.md
Resources/config/jackalope_doctrine_dbal.xml
composer.json

symfony automatically makes it lazy if ocramius/proxy-manager is available. otherwise the hint is ignored without causing any error.
replace https://github.com/doctrine/DoctrinePHPCRBundle/pull/339

mark schema listener as lazy

---

.styleci.yml
composer.json
src/CacheWarmer/UniqueNodeTypeCacheWarmer.php
src/DataCollector/AbstractPHPCRDataCollector.php
src/DependencyInjection/Compiler/DoctrinePhpcrMappingsPass.php
src/Form/ChoiceList/PhpcrOdmQueryBuilderLoader.php
src/Form/DoctrinePHPCRExtension.php
src/Form/PhpcrOdmTypeGuesser.php
src/Form/Type/DocumentType.php
src/Mapping/Driver/XmlDriver.php
src/Mapping/Driver/YamlDriver.php
src/Resources/config/odm.xml
src/Test/RepositoryManager.php
tests/Fixtures/App/DataFixtures/PHPCR/LoadData.php
tests/Functional/Form/PHPCRTypeGuesserTest.php
tests/Functional/Form/Type/DocumentTypeTest.php
tests/Unit/DependencyInjection/DoctrinePHPCRExtensionTest.php
tests/Unit/EventListener/LocaleListenerTest.php
tests/Unit/Form/DataTransformer/DocumentToPathTransformerTest.php
tests/Unit/Form/DataTransformer/PHPCRNodeToPathTransformerTest.php
tests/Unit/Form/Type/PHPCRReferenceTypeTest.php
tests/Unit/Initializer/InitializerManagerTest.php

Requires explicitly doctrine/persistence package and changes namespace to be compatible with version 2.0.

Allow doctrine/persistence 2.0

---

src/DependencyInjection/Configuration.php

There seems a query cache implemented in the doctrine dbal [CachedClient](https://github.com/jackalope/jackalope-doctrine-dbal/blob/85980bc641c3c8024823d791465471885babf56a/src/Jackalope/Transport/DoctrineDBAL/CachedClient.php#L592) but actually it is not possible to configured it over the repository.
Had this a specific case, was there any issues with invalidation or why this was not implemented? There seems to be an issue here https://github.com/doctrine/DoctrinePHPCRBundle/issues/4 whichs links to https://github.com/doctrine/phpcr-odm/issues/427 but actually it seems we are not using `doctrine/phpcr-odm` package or atleast my composer doesn't output it.

Add possibility to implement a query cache

---

.github/workflows/test-application.yaml
CHANGELOG.md
composer.json
tests/Fixtures/App/config/framework.yaml

this used to be pulled in automatically but now that doctrine/cache is
abandoned, it is no longer pulled in automatically.
we should switch to PSR-6 or PSR-16 cache and use e.g. symfony/cache,
but jackalope depends on doctrine cache directly for now.

this bundle depends on doctrine/cache

---

.github/workflows/test-application.yaml
UPGRADE-2.4.md
composer.json
src/DependencyInjection/DoctrinePHPCRExtension.php
src/Form/ChoiceList/PhpcrOdmQueryBuilderLoader.php
src/Form/Type/DocumentType.php
tests/Fixtures/App/Kernel.php
tests/Fixtures/App/bin/console
tests/Functional/BaseTestCase.php
tests/Functional/Command/NodeDumpCommandTest.php
tests/Functional/Form/ChoiceList/PhpcrOdmQueryBuilderLoaderTest.php
tests/Functional/Form/PHPCRTypeGuesserTest.php
tests/Functional/Form/Type/DocumentTypeTest.php
tests/Unit/Form/Type/PHPCRReferenceTypeTest.php
tests/Unit/Form/Type/PathTypeTest.php

This PR adds symfony 6 support and needs to drop symfony 3.4 support because of incompatibilities in dependencies (symfony/debug vs symfony/error-handler)
I also needed to add some typehints for symfony 6, which are actually BC breaks on the form classes. But I've based my changes on this PR where the BC-breaks were allow but documented on the changelog. https://github.com/doctrine/DoctrineMongoDBBundle/pull/710/files#diff-ac283054e672754976fb16579fe1793963bb79c2410f0c6e0718d5dda58104a2R16

Allow symfony 6

---

src/Resources/config/odm.xml

this form type has been removed for version 3 of the bundle. remove the service definition to avoid warnings from the container linter.
fix #364

remove obsolete PHPCRODMReferenceCollectionType service definition
