doctrine/DoctrinePHPCRBundle

DependencyInjection/Configuration.php, DependencyInjection/DoctrinePHPCRExtension.php, Tests/Unit/DependencyInjection/ConfigurationTest.php, Tests/Unit/DependencyInjection/DoctrinePHPCRExtensionTest.php
Adds support for setting a custom locale chooser via. configuration and DI tags.
=> [WIP] Added support for custom locale chooser

DoctrinePHPCRBundle.php
See https://github.com/doctrine/DoctrinePHPCRBundle/pull/191
=> Close connections and clear managers on shutdown

DependencyInjection/Configuration.php, DependencyInjection/DoctrinePHPCRExtension.php, Resources/views/Collector/phpcr.html.twig, Tests/Unit/DependencyInjection/ConfigurationTest.php
Added support for collecting the backtrace leading up to PHPCR calls
Depends: https://github.com/jackalope/jackalope/pull/282
=> Added support for caller debug in PHPCR collector

.travis.yml, DependencyInjection/DoctrinePHPCRExtension.php, Form/Type/PHPCRODMReferenceCollectionType.php, Form/Type/PHPCRReferenceType.php, Form/Type/PathType.php, Tests/Unit/Form/Type/PathTypeTest.php, composer.json
A try at fixing the deprecation notices.
=> Fix Symfony deprecation notices

DependencyInjection/DoctrinePHPCRExtension.php, Tests/Unit/DependencyInjection/DoctrinePHPCRExtensionTest.php
fix omission in https://github.com/doctrine/DoctrinePHPCRBundle/pull/208
=> define the admin session

Tests/Functional/GenericInitializerTest.php
trying to reproduce #219
@WouterJ locally, the test succeeds for me with the latest versions. any idea how we can make it fail to figure out what we need to fix?
=> test initializer

composer.json
* Use carets when it's needed
* Remove useless OR statements
* prefer-stable option for clearest config file
=> Simplify composer.json

DoctrinePHPCRBundle.php, OptionalCommand/ODM/DocumentConvertTranslationCommand.php, composer.json
fix #230
also update minimal requirements.
=> integrate the convert translations command

.travis.yml, Form/PhpcrOdmTypeGuesser.php, Form/Type/DocumentType.php, Form/Type/PHPCRReferenceType.php, Form/Type/PathType.php, Tests/Functional/Form/PHPCRTypeGuesserTest.php, Tests/Functional/Form/Type/DocumentTypeTest.php, Tests/Resources/DataFixtures/PHPCR/LoadData.php, Tests/Resources/Fixtures/config/multiple.yml, Tests/Resources/Fixtures/config/single.yml, Tests/Unit/DependencyInjection/ConfigurationTest.php
=> deprecations warning only for new versions

DoctrinePHPCRBundle.php
=> Close connection on bundle shutdown only if session is the Jackalope one

Command/LoadFixtureCommand.php
This is just like the change in DoctrineFixturesBundle https://github.com/doctrine/DoctrineFixturesBundle/pull/140/files
=> Load fixtures from a file

Form/DataTransformer/ReferenceManyCollectionToArrayTransformer.php, Form/Type/PHPCRODMReferenceCollectionType.php
=> Fixed typos

CHANGELOG.md, DependencyInjection/Configuration.php, DependencyInjection/DoctrinePHPCRExtension.php, Tests/Unit/DependencyInjection/ConfigurationTest.php
=> Changed to match the LocaleListener constructor

Validator/Constraints/ValidPhpcrOdmValidator.php
This fixes Symfony 3 support.
If you want, you can click "update" on http://pr-329-hrwsaa77j2pyk.eu.platform.sh/en/admin/app/demoseocontent/cms/content/company/edit to see the failure yourself :smiley:
=> Use buildViolation on Symfony 2.5+

CHANGELOG.md, DependencyInjection/DoctrinePHPCRExtension.php, Resources/config/jackalope.xml, Resources/config/jackalope_doctrine_dbal.xml
=> only load schema services when dbal is used

composer.json, phpunit.xml.dist
As request in #290, I've updated the `master` TestCase to PHPUnit 6.
=> Updated to PHPUnit 6

src/Resources/config/commands.xml
LoadFixtureCommand class was not loaded. Ref issue: https://github.com/doctrine/DoctrinePHPCRBundle/issues/300
=> Enable doctrine:phpcr:fixtures:load command

.travis.yml, .travis/phpcr_odm_doctrine_dbal.sh, composer.json, phpunit.xml.dist, src/DataFixtures/PHPCRExecutor.php, src/Test/RepositoryManager.php, tests/Fixtures/App/Kernel.php, tests/Fixtures/App/bin/console, tests/Fixtures/App/config/bundles.php, tests/Fixtures/App/config/config.php, tests/Fixtures/App/config/doctrine.yaml, tests/Fixtures/App/config/framework.yaml, tests/Functional/BaseTestCase.php, tests/Functional/Form/ChoiceList/PhpcrOdmQueryBuilderLoaderTest.php, tests/Functional/Form/PHPCRTypeGuesserTest.php, tests/Functional/Form/Type/DocumentTypeTest.php, tests/Functional/Initializer/GenericInitializerTest.php, tests/Web/WebProfilerTest.php
adjust to best practices as per https://symfony.com/doc/current/bundles/best_practices.html#continuous-integration
fix #306
=> cleanup build matrix

CHANGELOG.md, src/DependencyInjection/DoctrinePHPCRExtension.php, src/Resources/config/odm.xml
fix #325
documentation adjustments is in https://github.com/symfony-cmf/symfony-cmf-docs/pull/848
=> adjust service name alias for autowiring

src/DependencyInjection/DoctrinePHPCRExtension.php
=> Fixes non exist services in service build on debug:config commands

CHANGELOG.md, src/Command/LoadFixtureCommand.php
=> getRootDir has been removed in symfony 5

src/DependencyInjection/DoctrinePHPCRExtension.php
Follow up for https://github.com/doctrine/DoctrinePHPCRBundle/pull/362#discussion_r767875492
=> Add return types to private methods
